services:

  flask:
    build: .
    environment:
      FLASK_ENV: development
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/usr/src/app
    ports:
      - 5000:5000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: tablic
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

volumes:
  mongo-data:
  mongo-configdb:
    