services:

  db:
    image: mongo:latest
    restart: always
    logging:
      driver: none
    environment:
      MONGO_INITDB_DATABASE: tablic
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db
      - mongo-configdb:/data/configdb

  backend:
    image: tablic-backend:latest
    build: 
      context: ./backend
    restart: always
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env
    volumes:
      - ./backend:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db


volumes:
  mongo-data:
  mongo-configdb:
