name: Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv
      run: pip install pipenv

    - name: Cache pipenv
      id: cache
      uses: actions/cache@v2
      with:
        path: ~/.local/share/virtualenvs
        key: ${{ runner.os }}-pipenv-${{ hashFiles('Pipfile.lock') }}

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true'
      working-directory: ${{ env.working-directory }}
      run: pipenv install --dev

    - name: Run linters
      working-directory: ${{ env.working-directory }}
      run: pipenv run pylint app --fail-under 9.5
