name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  testing:
    runs-on: ubuntu-latest
    env:
      working-directory: ./backend
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pipenv
        pipenv lock --dev --requirements > requirements.txt
        pip install -r ./requirements.txt
      working-directory: ${{ env.working-directory }}
    - name: Run tests
      run: |
        pytest --cov=app --cov=tests
      working-directory: ${{ env.working-directory }}
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      with:
        directory: ${{ env.working-directory }}
