name: Tests

on: [push, pull_request]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipenv
      run: pip install pipenv
    - name: Install dependencies
      run: |
        cd backend
        pipenv install --dev
    - name: Run tests
      run: pytest --cov=app
    - name: Upload coverage
      uses: codecov/codecov-action@v1
      